### ISSUE TITLE
Grant request instead of Implicit Flow + Walkthru

### ISSUE THREAD

**Issue by ftarlao** [authlete/java-oauth-server#1]
I'm studying Oauth/OpenID Connect and available implementations, I have installed your AS/RS demo and I have understood that you implemented an 'implicit flow'. I have understood that the implicit flow generates only a short living token and does not assign to the client a long living grant.

Does your demo support the Grant+token interaction flow?.. and in case can you add to your demo a guide regarding this case (http requests and so on)?

I'm just learning at the moment, so, I hope to have understood the basics well.
Regards

**Comment by TakahikoKawasaki** [comment]
> the implicit flow generates only a short living token and does not assign to the client a long living grant.

Not always. **Access tokens** issued by [Implicit Flow](https://tools.ietf.org/html/rfc6749#section-4.2) can be long-lived tokens depending on the configuration of the authorization server. On the other hand, **authorization codes** issued by [Authorization Code Flow](https://tools.ietf.org/html/rfc6749#section-4.1) are short-lived because [4.1.2. Authorization Response](https://tools.ietf.org/html/rfc6749#section-4.1.2) in [RFC 6749](https://tools.ietf.org/html/rfc6749) says as follows:

> _REQUIRED.  The authorization code generated by the authorization server.  **The authorization code MUST expire shortly** after it is issued to mitigate the risk of leaks.  A maximum authorization code lifetime of 10 minutes is RECOMMENDED.  The client MUST NOT use the authorization code more than once.  If an authorization code is used more than once, the authorization server MUST deny the request and SHOULD revoke (when possible) all tokens previously issued based on that authorization code.  The authorization code is bound to the client identifier and redirection URI._

BTW,

> Does your demo support the Grant+token interaction flow?

What is "Grant+token interaction flow"? RFC 6749 defines 4 authorization flows as listed below and I cannot understand what you mean by "Grant+token interaction flow".

1. [Authorization Code Flow](https://tools.ietf.org/html/rfc6749#section-4.1)
2. [Implicit Flow](https://tools.ietf.org/html/rfc6749#section-4.2)
3. [Resource Owner Password Credentials Flow](https://tools.ietf.org/html/rfc6749#section-4.3)
4. [Client Credentials Flow](https://tools.ietf.org/html/rfc6749#section-4.4)

Please see "[Diagrams And Movies Of All The OAuth 2.0 Flows](https://medium.com/@darutk/diagrams-and-movies-of-all-the-oauth-2-0-flows-194f3c3ade85)" to understand differences among the flows.

java-oauth-server already supports all the flows.

**Comment by ftarlao** [comment]
Thank you,
I have concluded from the diagrams that I was looking for the 'Authentication Code Flow' (.. is the one that I have learned during classes). From RFC I was not able to assign the label 'Authentication Code Flow' to the workflow I was looking at, I have thought it was the 'vanilla' one.
Now I (hopefully)have a clearer idea, I'll try to request a code 'grant' to your AS demo by following the RFC.
It would be nice to have any tips/examples, in your AS demo wiki, on how to consume the authorization endpoint in a 'Authorization Code Flow'.
Thanks for all explanations.
Regards

**Comment by TakahikoKawasaki** [comment]
# Authorization Code Flow
## Request To Authorization Endpoint

    GET {Authorization Endpoint}
      ?response_type=code            // Required
      &client_id={Client ID}         // Required
      &redirect_uri={Redirect URI}   // Conditionally Required
      &scope={Scopes}                // Scopes, Space-delimited
      &state={Arbitrary String}      // Recommended
      HTTP/1.1
    HOST: {Authorization Server}

## Response From Authorization Endpoint

    HTTP/1.1 302 Found
    Location: {Redirect URI}
      ?code={Authorization Code}    // Always included
      &state={Arbitrary String}     // Included if the authorization request included 'state'.

## Request To Token Endpoint

    POST {Token Endpoint} HTTP/1.1
    Host: {Authorization Server}
    Content-Type: application/x-www-form-urlencoded

    grant_type=authorization_code  // Required
    &code={Authorization Code}     // Required. The 'code' in the authorization response.
    &redirect_uri={Redirect URI}   // Required if the authorization request included 'redirect_uri'.

## Response From Token Endpoint

    HTTP/1.1 200 OK
    Content-Type: application/json;charset=UTF-8
    Cache-Control: no-store
    Pragma: no-cache

    {
      "access_token":"{Access Token}",    // Always included
      "token_type":"{Token Type}",        // Always included
      "expires_in":{Lifetime},            // Optional. Lifetime in seconds
      "refresh_token":"{Refresh Token}"   // Optional
    }
